apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
    kubernetes.io/service-account.name: internal-app
    avp.kubernetes.io/path: "secret/helloworld"
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>
