apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    env: prod
spec:
  type: ClusterIP
  selector:
    app: petclinic   # Selecting PODS with those Labels
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
